spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13456979826a
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&useSLL=true&characterEncoding=UTF-8

mybatis:
  type-aliases-package: cn.xjt.pojo
  mapper-locations: classpath:/mapper/*.xml